language: node_js

node_js:
- 8.9.4

sudo: required

jobs:
  include:
    - stage: install_test
      script:
        - cd client/mobile_broswer
        - yarn
        - yarn lint
        - yarn build
        - cd ../..
        - cd server
        - yarn
        - cd ..
    - stage: deploy
      addons:
        ssh_known_hosts: 118.25.77.208
      script:
        - openssl aes-256-cbc -K $encrypted_8010cd2da6b2_key -iv $encrypted_8010cd2da6b2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host 118.25.77.208\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - pwd
      after_success:
        - ssh root@118.25.77.208 'bash -s' < deploy.sh

notifications:
  email: false